# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('delete', 'delete'), ('modify', 'modify'), ('create', 'create')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Diff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_date', models.DateTimeField(auto_now_add=True)),
                ('actions', models.ManyToManyField(to='osmdata.Action')),
            ],
        ),
        migrations.CreateModel(
            name='OSMElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osmid', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelationMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('role', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k', models.CharField(max_length=255)),
                ('v', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WayNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('osmelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='osmdata.OSMElement')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
            bases=('osmdata.osmelement',),
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('osmelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='osmdata.OSMElement')),
            ],
            bases=('osmdata.osmelement',),
        ),
        migrations.CreateModel(
            name='Way',
            fields=[
                ('osmelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='osmdata.OSMElement')),
            ],
            bases=('osmdata.osmelement',),
        ),
        migrations.AddField(
            model_name='tag',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='osmdata.OSMElement'),
        ),
        migrations.AddField(
            model_name='relationmember',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_element', to='osmdata.OSMElement'),
        ),
        migrations.AddField(
            model_name='action',
            name='new',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_for', to='osmdata.OSMElement'),
        ),
        migrations.AddField(
            model_name='action',
            name='old',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_for', to='osmdata.OSMElement'),
        ),
        migrations.AddField(
            model_name='waynode',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osmdata.Node'),
        ),
        migrations.AddField(
            model_name='waynode',
            name='way',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osmdata.Way'),
        ),
        migrations.AddField(
            model_name='way',
            name='nodes',
            field=models.ManyToManyField(through='osmdata.WayNode', to='osmdata.Node'),
        ),
        migrations.AddField(
            model_name='relationmember',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osmdata.Relation'),
        ),
        migrations.AddField(
            model_name='relation',
            name='members',
            field=models.ManyToManyField(related_name='parent_relation', through='osmdata.RelationMember', to='osmdata.OSMElement'),
        ),
    ]
