# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmdata', '0003_osmelement_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='osmelement',
            name='changeset',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='osmelement',
            name='uid',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='osmelement',
            name='user',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
