# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmdata', '0004_auto_20161012_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='osmelement',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
