# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmdata', '0006_auto_20161012_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='lon',
            field=models.FloatField(null=True),
        ),
    ]
