# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmdata', '0008_auto_20170421_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='osmelement',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
