# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 15:01
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osmdata', '0009_osmelement_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='latlon',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=3857),
        ),
    ]
