# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 15:21
from __future__ import unicode_literals

from django.contrib.gis.gdal import SpatialReference, CoordTransform
from django.contrib.gis.geos import Point
from django.db import migrations


def planify_coords(lat, lon):
    """ See osmdata/geo_utils.py """
    planification = CoordTransform(
        SpatialReference(4326), SpatialReference(3857))
    point = Point(lon, lat, srid=4326)
    point.transform(planification)
    return point


def compute_node_geo_point(apps, schema_editor):
    Node = apps.get_model("osmdata", "Node")
    for node in Node.objects.all():
        if not node.latlon:
            node.latlon = planify_coords(node.lat, node.lon)
            # calls default save() not ours from models.py
            node.save()


class Migration(migrations.Migration):

    dependencies = [
        ('osmdata', '0010_node_latlon'),
    ]

    operations = [
        migrations.RunPython(compute_node_geo_point)
    ]
