# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osmdata', '0011_auto_20170824_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osmelement',
            name='bounds',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='osmdata.Bounds'),
        ),
    ]
