# Generated by Django 2.0 on 2017-12-05 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osmdata', '0012_auto_20170829_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='new',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_for', to='osmdata.OSMElement'),
        ),
        migrations.AlterField(
            model_name='action',
            name='old',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='old_for', to='osmdata.OSMElement'),
        ),
        migrations.AlterField(
            model_name='osmelement',
            name='bounds',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='osmdata.Bounds'),
        ),
    ]
