# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('osmdata', '0012_auto_20170829_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_tag', models.CharField(max_length=100)),
                ('is_tag_action', models.BooleanField()),
                ('is_geometric_action', models.BooleanField()),
                ('action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='osmdata.Action')),
                ('added_tags', models.ManyToManyField(related_name='added_on_reports', to='osmdata.Tag')),
                ('modified_tags_new', models.ManyToManyField(related_name='modified_new_on_reports', to='osmdata.Tag')),
                ('modified_tags_old', models.ManyToManyField(related_name='modified_old_on_reports', to='osmdata.Tag')),
                ('removed_tags', models.ManyToManyField(related_name='removed_on_reports', to='osmdata.Tag')),
            ],
        ),
    ]
