# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diffanalysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionreport',
            name='main_tag',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
