# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diffanalysis', '0002_auto_20170901_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionreport',
            name='version_delta',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
